---
- name: update installed packages via dnf
  dnf:
    name: "*, dnf-utils"
    state: latest

- name: add docker-ce repository
  shell: |
    sudo dnf-config-manager \
    --add-repo \
    {{ fedora_baseurl }}
