---

- name: create docker volume for portainer data
  shell: >
    docker volume create portainer_data

- name: install portainer server container
  shell: >
    docker run -d -p 8000:8000 -p 9443:9443 --name portainer \
    --restart=always \
    --privileged
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v portainer_data:/data \
    portainer/portainer-ce:latest
  register: status

- debug:
    msg: "{{ status }}"
