---
- name: update installed packages via yum
  include_tasks: "{{ansible_distribution|lower}}_repo.yml"

- name: install docker packages
  package:
    name: "{{ docker_packages | join(',') }}"
    state: present

- name: add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"

- name: enable docker service
  service:
    name: docker
    enabled: yes
    state: started
